version: '3.7'

networks:
  contract-private:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.1.0/24

services:

  contract-testnet:
    build: 
      context: ./images/eth-testnet
      dockerfile: Dockerfile.main
    container_name: "contract-testnet"
    deploy:
      resources:
        limits:
          cpus: "1"
    networks:
      contract-private:
        ipv4_address: 10.5.1.2
  contract-light:
    build:
      context: ./images/eth-testnet
      dockerfile: Dockerfile.light
    container_name: "contract-light"
    deploy:
      resources:
        limits:
          cpus: "0.5"
    ports: 
      - 9545:8545
    networks:
      contract-private:
        ipv4_address: 10.5.1.3
  contract-relay:
    build:
      context: ./images/eth-testnet 
      dockerfile: Dockerfile.relay 
    container_name: "contract-relay"
    networks:
      contract-private:
        ipv4_address: 10.5.1.4
