version: '3.7'

networks:
  contract-private:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.1.0/24

services:

  contract-rpc-cors-proxy:
    build: 
      context: ./images/rpc-cors-proxy
    container_name: "contract-rpc-cors-proxy"
    environment:
      - PROXY_TARGET_HOST=10.5.1.3
      - PROXY_TARGET_PORT=8545
      - NGINX_PORT=80
    command: /bin/sh -c "envsubst '$${NGINX_PORT},$${PROXY_TARGET_HOST},$${PROXY_TARGET_PORT}' < /etc/nginx/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    networks:
      contract-private:
        ipv4_address: 10.5.1.10
  contract-testnet:
    build: 
      context: ./images/eth-testnet
      dockerfile: Dockerfile.main
    container_name: "contract-testnet"
    deploy:
      resources:
        limits:
          cpus: "1"
    networks:
      contract-private:
        ipv4_address: 10.5.1.2
  contract-light:
    build:
      context: ./images/eth-testnet
      dockerfile: Dockerfile.light
    container_name: "contract-light"
    deploy:
      resources:
        limits:
          cpus: "0.5"
    ports: 
      - 9545:8545
    networks:
      contract-private:
        ipv4_address: 10.5.1.3
  contract-relay:
    build:
      context: ./images/eth-testnet 
      dockerfile: Dockerfile.relay 
    container_name: "contract-relay"
    networks:
      contract-private:
        ipv4_address: 10.5.1.4
  blockscout-db:
    build:
      context: ./images/blockscout-db
    container_name: "blockscout-db"
    restart: "always"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=
        - POSTGRES_HOST_AUTH_METHOD=trust
        - POSTGRES_DB=explorer
    networks:
      contract-private:
        ipv4_address: 10.5.1.6
  blockscout:
    depends_on:
      - blockscout-db
      - contract-light
      - contract-testnet
    image: blockscout/blockscout
    container_name: "blockscout"
    environment:
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=http://10.5.1.10:80
      - ETHEREUM_JSONRPC_TRACE_URL=http://10.5.1.10:80
      - ETHEREUM_JSONRPC_WS_URL=ws://10.5.1.3:3334
      - DATABASE_URL=postgresql://postgres:@10.5.1.6:5432/explorer?sslmode=enable&ssl=true
      - COIN=ETH
      - NETWORK=ETH
      - BLOCKSCOUT_HOST=10.5.1.5
      - BLOCKSCOUT_PROTOCOL=http
      - PORT=4000
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    restart: always
    networks:
      contract-private:
        ipv4_address: 10.5.1.5
