version: '3.7'

networks:
  contract-private:
    driver: bridge
    ipam:
      config:
      - subnet: 10.5.1.0/24

services:

  contract-rpc-cors-proxy:
    build: 
      context: ./images/rpc-cors-proxy
    container_name: "contract-rpc-cors-proxy"
    environment:
      - PROXY_TARGET_HOST=10.5.1.3
      - PROXY_TARGET_PORT=8545
      - NGINX_PORT=80
    command: /bin/sh -c "envsubst '$${NGINX_PORT},$${PROXY_TARGET_HOST},$${PROXY_TARGET_PORT}' < /etc/nginx/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    networks:
      contract-private:
        ipv4_address: 10.5.1.10
  contract-testnet:
    build: 
      context: ./images/eth-testnet
      dockerfile: Dockerfile.main
    container_name: "contract-testnet"
    deploy:
      resources:
        limits:
          cpus: "1"
    networks:
      contract-private:
        ipv4_address: 10.5.1.2
  contract-light:
    build:
      context: ./images/eth-testnet
      dockerfile: Dockerfile.light
    container_name: "contract-light"
    deploy:
      resources:
        limits:
          cpus: "0.5"
    ports: 
      - 9545:8545
    networks:
      contract-private:
        ipv4_address: 10.5.1.3
  contract-relay:
    build:
      context: ./images/eth-testnet 
      dockerfile: Dockerfile.relay 
    container_name: "contract-relay"
    networks:
      contract-private:
        ipv4_address: 10.5.1.4
