[Eth]
NetworkId = 1
SyncMode = "full"
NoPruning = false
NoPrefetch = false
UltraLightFraction = 75
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 154
TrieCleanCacheJournal = "triecache"
TrieCleanCacheRejournal = 3600000000000
TrieDirtyCache = 256
TrieTimeout = 3600000000000
SnapshotCache = 102
Preimages = false
EnablePreimageRecording = false

[Eth.Ethash]
CacheDir = ".ethash"
CachesInMem = 1
CachesOnDisk = 1
CachesLockMmap = false
DatasetDir = ".ethash"
DatasetsInMem = 1
DatasetsOnDisk = 1
DatasetsLockMmap = false
PowMode = 0
NotifyFull = false

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
WSHost = "0.0.0.0"

[Node.P2P]
NoDiscovery = true
ListenAddr = ":30303"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000